// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQBbsTT7Djzvh1JVwG28euuvGkgvTAZtk',
    appId: '1:674649420591:web:15bd3f5563f4fe205f67da',
    messagingSenderId: '674649420591',
    projectId: 'taskai-f5211',
    authDomain: 'taskai-f5211.firebaseapp.com',
    storageBucket: 'taskai-f5211.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlL9JcrO8RsrRdHLctMBoeSnaIwA9zpgI',
    appId: '1:674649420591:android:c055d012629994ac5f67da',
    messagingSenderId: '674649420591',
    projectId: 'taskai-f5211',
    storageBucket: 'taskai-f5211.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmEwPtlmDjg-peGIjBzsnKC8OSqghyj44',
    appId: '1:674649420591:ios:7b19ff3274efc79d5f67da',
    messagingSenderId: '674649420591',
    projectId: 'taskai-f5211',
    storageBucket: 'taskai-f5211.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmEwPtlmDjg-peGIjBzsnKC8OSqghyj44',
    appId: '1:674649420591:ios:7b19ff3274efc79d5f67da',
    messagingSenderId: '674649420591',
    projectId: 'taskai-f5211',
    storageBucket: 'taskai-f5211.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQBbsTT7Djzvh1JVwG28euuvGkgvTAZtk',
    appId: '1:674649420591:web:87e8206ec8eaab1a5f67da',
    messagingSenderId: '674649420591',
    projectId: 'taskai-f5211',
    authDomain: 'taskai-f5211.firebaseapp.com',
    storageBucket: 'taskai-f5211.firebasestorage.app',
  );
}
